const tmpSMSSenderList = [
  {
    senderName: 'ACFC',
    templates: {
      mobifone: [
        'Cam on ban da dong hanh cung.{0,200}danh tang rieng ban.{0,50}code.{0,50} ap dung tai.{0,90}Tel.{0,50}',
        'Cam on Quy Khach.{0,50}DH.{0,80}Quy Khach.{0,50}LH.{0,20}',
        'Cam on Quy khach da dat hang trong chuong trinh.{0,50}Hien tai, do luong don hang dang qua tai, nen thoi gian giao hang co the tre hon so voi du kien. ACFC se co gang chuyen don hang den Quy khach trong thoi gian som nhat. Du kien tu.{0,50}Chung toi chan thanh xin loi vi su cham tre nay, mong Quy khach thong cam. Moi thac mac vui long lien he Hotline 19003038 de duoc ho tro. Tran trong.',
        'Kinh moi Quy Khach Hang den trao doi cung nhan hang.{0,200}Quy khach vui long mang theo CMND de lam thu tuc ra vao toa nha. Xin cam on quy khach. Tran trong.',
        'MANGO gui rieng ban chuong trinh.{0,150}AP DUNG TAI.{0,100}',
        '.{0,30}Your ACFC Card accumulate to.{0,100}Please update your address at link https://bit.ly/.{0,70}',
        'DH.{0,80}Cam on Quy khach da mua sam cung ACFC. Vui long lien he.{0,100}',
        'ACFC - Mã OTP của bạn là.{0,20}Hiệu lực của mã OTP là.{0,80}',
        'OWNDAYS tang rieng.{0,30}co hoi thang hang the ACFC.{0,100}HSD.{0,30}',
        'CALVIN KLEIN-GUI.{0,100}MUA SAM THEM.{0,100}tai cac CH CK toan quoc.LH 02873029399',
        'OWNDAYS tang rieng.{0,40}co hoi thang hang the ACFC.{0,120}',
        'CALVIN KLEIN- KINH GUI.{0,60}DE NANG HANG THE VOI CHUONG TRINH.{0,60}',
        'Chao mung 501 Day, Levis cam on ban voi ma tru 500k [^.]{0,30} cho HD tu .{0,50} Co dieu kien ap dung. LH 19003038.',
        'HAPPY BIRTHDAY! .{0,50} KHI MUA CAC SAN PHAM NGUYEN GIA TAI CH LEVIS TOAN QUOC. AP DUNG TU .{0,40} LH .{0,20}',
        'HAPPY BIRTHDAY! ACFC tang Quy Khach code.{0,150}Vui long trinh CMND & SMS. Chi tiet http://bit.ly/.{0,30}',
        'NIKE gui tang.{0,200}vui long mang tin nhan nay den CH NIKE_ACFC bat ky de su dung. Cam on.{0,30}da luon ung ho NIKE.',
        'ACFC tang rieng.{0,160}hang hieu danh cho phu nu. Chi trong.{0,70}',
        'COTTON ON gui ban ma mua hang:[^.]{0,30}. Vui long mang theo tin nhan nay khi mua sam tai Cotton On Vincom Dong Khoi tu 16-18/10. LH: 02873014799',
        'Ma kich hoat tai khoan la[^.]{0,30}co hieu luc trong 5 phut, Quy khach vui long kich hoat tai khoan de nhan duoc cac dac quyen uu dai danh cho chu tai khoan.',
        'Cam on Quy khach da dat hang tai ACFC. De cap nhat thong tin moi nhat ve CTKM hap dan, truy cap ngay http://acfc.com.vn hoac lien he Hotline 1900 3038.',
        'Nham ho tro Khach hang Sinh nhat Thang 3, ACFC gia han su dung code .{0,10} den .{0,20} tai tat ca Cua Hang. Code [^.]{0,30} &CMND. Chi tiet http://bit.ly/.{0,30}',
        '(DANH RIENG TANG BAN) Qua tang.{0,120}Chi ap dung tai cua hang .{0,5} cho sp nguyen gia.{0,50}',
        'Announcement! Your ACFC Card accumulated spending last 12 months is close to .{0,50}. Just add a bill ~.{0,10} before May31 for your own .{0,50}. Tel 19003038',
        'Congratulation! Your ACFC Card accumulate to .{0,30} for spending last 12months, Please update your address at link https://bit.ly/.{0,30} for receive VIPcard',
        'Chuc mung Quy Khach dang ky thanh cong.{0,50}Ma qua tang.{0,50}SP nguyen gia & HSD den .{0,30}LH 028 39397999',
        '.{0,80}DE GIU MUC HANG THE.{0,100}TRONG DIP.{0,80}tai cac CH CK toan quoc.{0,20}',
        'Don hang[^.]{0,40}duoc dat thanh cong. Cam on Quy khach da mua sam cung ACFC. Vui long lien he Hotline.{0,30}de duoc ho tro ve thoi gian giao hang.',
        'Chao nguoi ban thanh vien, PARFOIS danh rieng den ban .{0,150} khi doc ma [^.]{0,50} cho nhan vien CH. Chi Tiet: 02873018499.',
        'DH .{0,20} duoc dat thanh cong. Ma kiem tra DH.{0,50}tai.{0,50}https://brd.to.{0,50}Cam on QK da mua sam cung ACFC. LH.{0,20}de duoc ho tro.',
        'Chuc Mung! Doanh so tich luy trong 12thang gan nhat cua Quy Khach dat hang .{0,30} Vui long cap nhat dia chi tai link https://bit.ly/.{0,30} de nhan VIPcard',
        'Happy Birthday! ACFC gui ma giam .{0,20} SP nguyen gia cho 1 HD toi da 10tr tai CH ACFC. HSD den .{0,30}. Code [^.]{0,20} & CMND. Chi tiet http://bit.ly/.{0,30}',
        'Cam on Quy khach da dat hang tai ACFC. De cap nhat thong tin moi nhat ve CTKM hap dan, truy cap ngay www.acfc.com.vn hoac lien he Hotline 1900 3038.',
        '.{0,30}danh tang khach.{0,200}He thong CH: http://bit.ly/.{0,30}',
        'Chuc mung Quy Khach dang ky thanh cong Chuong trinh thanh vien ACFC. Ma qua tang[^.]{0,50}giam 10% SP nguyen gia & HSD 15.4.2021 . LH 028 39397999',
        'Ma kich hoat tai khoan la[^.]{0,30}co hieu luc trong 5 phut, Quy khach vui long kich hoat tai khoan de trai nghiem mua sam hang hieu chinh hang tai ACFC.',
        'TOMMY HILFIGER- Special offer for valued customer: -20% Ecode[^.]{0,50}cho hang nguyen gia/for full price items. Ap dung tu/ Redeem from 21-27/9 tai CH Tommy/ at Tommy stores',
        'Birthday offer extension.{0,40}Enjoy code.{0,100}Use code with your ID card.{0,80}',
        'Cam on Quy khach da dat hang tai ACFC. De cap nhat thong tin moi nhat ve CTKM hap dan, truy cap ngay https://bit.ly/.{0,20} hoac lien he Hotline.{0,30}.',
        'TOMMY HILFIGER - Chi con thieu 3tr ban se tro thanh KH VIP. Tommy tang ban Ecode[^.]{0,40}giam 20% hang nguyen gia. Ap dung tu 21-27/9 tai tat ca CH Tommy',
        'CALVIN KLEIN-KINH GUI.{0,150}tai cac CH CK toan quoc.{0,30}',
        'ACFC chao[^.]{0,50}Cam on ban da dat hang tai ACFC.{0,50}Hien tai don hang[^.]{0,50}co cac san pham.{0,250}Mot lan nua xin chan thanh xin loi.{0,150}ACFC cam on ban, men chuc ban co nhieu niem vui trong cuoc song.',
        'TOMMY HILFIGER[^.]{0,5}Special offer for valued customer[^.]{0,50}cho hang nguyen gia/for full price items. Ap dung tu/ Redeem from 21-27/9 tai CH Tommy/ at Tommy stores',
        'TYPO gui tang ban ma [^.]{0,40} tri gia 100,000VND, ap dung HD 500,000VND tai cua hang .{0,100} Hotline:02873019599',
        '20/10 pn yeu chinh minh! ACFC tang rieng ban.{0,160}chi trong.{0,70}',
        'ACFC chan thanh xin loi ve su co huy don hang, mong Quy khach thong cam. ACFC goi ban ma qua tang[^.]{0,40}, giam gia 30% cac san pham nguyen gia khi mua hang tai www.acfc.com.vn . Thoi han su dung den het ngay .{0,20}Tran trong.',
        '.{0,50}ACFC xin phep gui tin nhan thong bao thay tong dai vi ACFC lien he dien thoai.{0,10}nhieu lan nhung khong duoc. ACFC xin thong bao huy don hang.{0,150}ACFC thanh that xin loi.{0,10}vi tinh huong nay, mong.{0,50}',
        '(Chuc mung sinh nhat quy khach hang)',
        'LEVIS TANG BAN MA .{0,100} TAI CAC CUA HANG LEVIS TOAN QUOC. LH 02839397999',
        'ACFC ra mat website TMDT. Tang .{0,50} Ma qua tang la .{0,30} su dung mua sam tai https://bit.ly/.{0,70}',
        'Happy Birthday! ACFC.{0,90}Birthday month.Code.{0,40}For details http://bit.ly/.{0,30}',
        'Don hang .{0,30} da duoc dat thanh cong. Cam on Quy khach da mua sam cung ACFC. Xin Quy khach luu y .{0,200}Vui long lien he hotline 1900 3038 de duoc ho tro.',
        '.{0,30}GIAM THEM.{0,100}CUA ACFC, TU.{0,100}DANH SACH CUA HANG: http://bit.ly/.{0,30}',
        'OVS TANG RIENG BAN ma code.{0,120}ap dung tai.{0,100}Hotline.{0,30}',
        'Chuc mung ngay.{0,50}ACFC tang ban code.{0,30}giam.{0,10}khi mua sp nguyen gia tai ACFC https://bit.ly/.{0,30}Ap dung tu.{0,30}',
        'ACFC tuyen dung.{0,120}De ung tuyen vui long dien thong tin theo link http://bit.ly/.{0,50}',
        'Cam on Quy khach da dat hang tai ACFC.{0,80}http://acfc.com.vn hoac lien he .{0,25}',
        '.{0,20}rat tiec vi khong the ho tro.{0,100}gui tang ma code.{0,200}vui long mang tin nhan nay den.{0,30}bat ky de su dung. Cam on.{0,50}',
        'Announcement: Your ACFC Card accumulate to[^.]{0,50}for spending last 12 months, for more details please contact us at 19003038 /email: cskh@acfc.com.vn',
        'Happy Birthday! ACFC gives 30%off full price/1 bill, 10milion max at ACFC stores on Birthday month.Code .{0,40} &IDcard.For details http://bit.ly/HPBDACFC',
        'TOMMY HILFIGER- Special offer for VIP card holders: -20% Ecode[^.]{0,40}cho hang nguyen gia/for full price items. Ap dung tu/ Redeem from .{0,60}',
        'Don hang .{0,30}duoc.{0,100}vui long truy cap www.acfc.com.vn hoac LH hotline.{0,30}Xin cam on.',
        'Congratulation! Your ACFC Card accumulate to .{0,50} for spending last 12months, Please update your address at link http://bit.ly/ACFCVIP for receive VIPcard',
        'Don hang .{0,30} da duoc.{0,150}LH hotline.{0,30}Xin cam on.',
        'Congratulation!Your ACFC Card accumulate to .{0,30} for spending last 12months, Please update your address at link https://bit.ly/.{0,30} for receive VIPcard',
        'TOMMY HILFIGER- Special offer for our valued customer: -20% Ecode[^.]{0,50}for full price items of FW20 collection at all Tommy stores from 21-27/9',
        'Chuc Mung! Doanh so tich luy trong 12thang gan nhat cua Quy Khach dat hang .{0,50}. Vui long cap nhat dia chi tai link http://bit.ly/ACFCVIP de nhan VIPcard',
        'LI XI DAC BIET! GAP tang rieng ban li xi.{0,55}khong cong gop voi CT khac.{0,45}',
        'Cac CH ACFC tai DA NANG da hoat dong tro lai, ACFC gui ma giam 30% Mung Sinh nhat Quy Khach trong .{0,20}, code[^.]{0,50}. Code ap dung .{0,100} Vui long trinh SMS & CMND de duoc ap dung. Chi tiet http://bit.ly/.{0,30}',
        'Don hang[^.]{0,50}duoc dat thanh cong. Cam on Quy khach da mua sam cung ACFC. Vui long lien he Hotline 1900 3038 de duoc ho tro ve thoi gian giao hang.',
        'ACFC[^.]{0,10}Ma OTP cua Quy khach la.{0,30}Hieu luc cua ma OTP la 5 phut.',
        'TYPO-Thuong hieu van phong pham, phu kien danh cho gioi tre den tu Uc, nay da chinh thuc co mat tai.{0,200}LH:02873011399',
        'TYPO gui tang ban ma [^.]{0,40} tri gia 100,000VND,ap dung HD 500,000VND tai TYPO Crescent Mall va TYPO Aeon Mall Ha Dong tu .{0,60}',
        'ACFC rat tiec vi khong the ho tro.{0,70}ACFC gui tang ma code.{0,200}vui long mang tin nhan nay den CH ACFC bat ky de su dung. Cam on.{0,30}da luon ung ho ACFC.',
        'ACFC xin thong bao, DH cua QK.{0,120}LH.{0,80}',
        'Cam on ban da dat hang tai ACFC don hang .{0,30}ACFC.{0,150}hotline.{0,30}Don hang se bi huy.{0,100}',
        'TOMMY HILFIGER - Chao don BST moi Thu Dong 2020, Tommy tang ban Ecode[^.]{0,50}giam 20% tat ca san pham nguyen gia. Ap dung tu 21-27/9 tai tat ca CH Tommy',
        'ACFC Thong bao! Doanh so tich luy 12thang gan nhat cua Quy Khach sap dat .{0,50}. Chi them 1 hoa don ~.{0,10} truoc 31/05 de so huu the .{0,50}. LH 19003038',
        'ACFC rat tiec san pham trong DH .{0,150}QK vui long kiem tra DH tai.{0,90}LH.{0,50}',
        'DOCKERS TANG RIENG BAN.{0,70}CHO TOAN BO SP NGUYEN GIA. AP DUNG.{0,100}',
        'TOMMY HILFIGER - To be VIP member, just spend 3mil more. Tommy offers -20% Ecode[^.]{0,50}for full price items at all Tommy stores from 21-27/9',
        'OWNDAYS TANG RIENG.{0,150}DANH SACH CH.{0,50}DIEU KHOAN & DIEU KIEN AP DUNG',
        '.{0,60}FCUK chuc mung Anh/Chi nhan duoc code.{0,150}Vui long trinh CMND & SMS',
        'ACFC rat tiec vi khong the ho tro.{0,70}ACFC gui tang ma code.{0,200}vui long mang tin nhan nay den CH ACFC bat ky de su dung. Cam on.{0,30}da luon ung ho ACFC.',
        'ACFC.{0,10}Ma OTP cua Quy khach la.{0,30}Hieu luc cua ma.{0,30}',
        'French Connection chuc mung Anh/Chi nhan duoc code.{0,150}Vui long trinh CMND & SMS',
        'Announcement: Your ACFC Card accumulate to .{0,50} for spending last 12 months, for more details please contact us at 19003038 /email: cskh@acfc.com.vn',
        'Happy Birthday! ACFC gui ma 30% SP nguyen gia cho 1 HD toi da 10tr tai CH ACFC trong thang SN. Code .{0,40} & CMND. Chi tiet http://bit.ly/HPBDACFC',
        'Do anh huong cua Covid-19, DH.{0,30}co the giao tre hon du kien. ACFC Mong quy khach thong cam. LH.{0,20}',
        'San pham.{0,90}Don hang se duoc van chuyen trong vong.{0,30}Cam on Quy Khach da mua sam cung ACFC.',
        '.{0,30}danh tang khach.{0,200}He thong CH: http://bit.ly/.{0,30}',
        'Chuc mung Quy Khach dang ky thanh cong Chuong trinh thanh vien ACFC. Ma qua tang[^.]{0,50}giam 10% SP nguyen gia & su dung trong ngay. LH 028 39397999',
        'TOMMY HILFIGER - Special offer for VIP card holders: -20% Ecode[^.]{0,40}for full price items at .{0,60}',
        '.{0,20}gui tang.{0,50}ma code.{0,150}Cam on.{0,50}',
        'Don hang .{0,30} da duoc huy thanh cong. De duoc ho tro thong tin hoac dat hang lai, vui long truy cap www.acfc.com.vn hoac LH hotline 1900 3038. Xin cam on.',
        'Don hang .{0,20} da duoc dat thanh cong. Cam on Quy khach da mua sam cung ACFC.{0,150}Vui long lien he hotline 1900 3038 de duoc ho tro ve thoi gian giao hang. Tran trong.',
        'Don hang .{0,30} da duoc.{0,150}LH hotline.{0,30}Xin cam on.',
        'Don hang .{0,20} da duoc dat thanh cong. Cam on Quy khach da mua sam cung ACFC.{0,150}Vui long lien he hotline 1900 3038 de duoc ho tro ve thoi gian giao hang. Tran trong.',
        'ACFC xin thong bao! Trong 12 thang gan nhat the thanh vien ACFC cua Quy khach dat hang muc .{0,50}, Chi tiet lien he: 19003038/ email: cskh@acfc.com.vn',
        'ACFC gui rieng ban e-voucher.{0,100}DS cac cua hang ap dung.{0,80}',
        'Chuc mung Quy khach nhan duoc ma qua tang .{0,30} khi dang ky tai khoan thanh cong. Truy cap https://bit.ly/.{0,30} de mua sam hang hieu chinh hang tai ACFC',
        'Don hang .{0,30}duoc.{0,100}vui long truy cap https://www.acfc.com.vn/ hoac LH hotline.{0,30}Xin cam on.',
        'Chao mung 501 Day, Levis cam on ban voi ma tru 500k [^.]{0,30} cho HD tu .{0,50} Co dieu kien ap dung. LH 19003038.',
        'Congratulation! Your ACFC Card accumulate to.{0,150}',
        'Happy Birthday! Enjoy code.{0,150}Use code with your ID card at ACFC store http://bit.ly/.{0,30}',
        'ACFC - Ma OTP cua ban la[^.]{0,30}. Hieu luc cua ma OTP la[^.]{0,30}hut',
        'LEVIS TANG RIENG BAN CO HOI TANG HANG THE ACFC.{0,120}AP DUNG.{0,100}',
        'Congratulation! Your ACFC Card accumulate to.{0,150}',
        'ACFC gui tang.{0,100}ap dung tai tat ca Cua Hang NIKE tai.{0,100}da luon ung ho ACFC.',
        'Chuc Mung! Doanh so tich luy trong 12thang gan nhat cua Quy Khach dat hang.{0,150}',
        '.{0,30}Tang rieng ban ma.{0,120}Chi ap dung tai cua hang .{0,5} cho sp nguyen gia.{0,50}',
        'CALVIN KLEIN-GUI.{0,100}MUA SAM THEM.{0,100}tai cac CH CK toan quoc.LH 02873029399',
        'Chuc Mung!Doanh so tich luy trong 12thang gan nhat cua Quy Khach dat hang .{0,50}Vui long cap nhat dia chi tai link https://bit.ly/.{0,30} de nhan VIPcard',
        'Happy Birthday! ACFC gui ma 30% ap dung SP nguyen gia & 1 HD toi da 10tr tai CH ACFC trong thang SN. Code .{0,30} & CMND. Chi tiet http://bit.ly/HPBDACFC',
        'Don hang .{0,30} da duoc huy thanh cong. De duoc ho tro thong tin hoac dat hang lai, vui long truy cap https://www.acfc.com.vn/ hoac LH hotline 1900 3038. Xin cam on.',
        'Cam on Quy khach da dat hang tai ACFC. De cap nhat nhung thong tin moi nhat tu ACFC, truy cap ngay http://bit.ly/acfc-vietnam hoac lien he Hotline 1900 3038.',
        'TOMMY HILFIGER -Danh Tang Khach VIP: Tang Ecode[^.]{0,50}giam 20% hang nguyen gia.{0,60} tai tat ca CH Tommy',
        'MANGO danh tang rieng Quy Khach.{0,150}http://bit.ly/.{0,30}',
        'ACFC gui tang.{0,100}ap dung tai tat ca.{0,150}da luon ung ho ACFC.',
        'ACFC gia han code chuc mung sinh nhat.{0,100}Vui long trinh CMND & SMS. Chi tiet.{0,80}',
        'ACFC - Mã OTP của bạn là.{0,10}Hiệu lực của mã OTP là 5 phút',
        'ACFC xin thong bao! Trong 12 thang gan nhat the thanh vien ACFC cua Quy khach dat hang muc[^.]{0,50}, Chi tiet lien he: 19003038/ email: cskh@acfc.com.vn',
        'CALVIN KLEIN- DE GIU HANG MUC THE,KINH MOI.{0,30}THAM GIA MUA SAM CUNG CHUONG TRINH.{0,100}',
        'ACFC TANG RIENG BAN MA VOUCHER.{0,100}AP DUNG.{0,40}TAI CAC CH.{0,100}',
        'CALVIN KLEIN-GUI.{0,50}, DE GIU MUC HANG THE, MOI.{0,20}MUA SAM THEM.{0,30}TRONG DIP MSS-UPTO.{0,30}tai cac CH CK toan quoc.{0,30}',
        'Don hang.{0,50}Cam on Quy khach da mua sam tai ACFC.{0,100}http://bit.ly/.{0,30}',
        'SHINING WITH US-Tang rieng ban ma.{0,120}khi mua san pham nguyen gia tai.{0,100}',
        'ACFC is happy to welcome you to exchange.{0,120}Hotline.{0,50}Thank you.{0,50}',
        'Kinh moi.{0,50}den doi san pham.{0,120}Chi tiet lien he.{0,50}Xin cam on quy khach.{0,50}',
      ],
    },
  },
  {
    senderName: 'MOTHERCARE',
    templates: {
      mobifone: [
        'MOTHERCARE - Mã OTP của bạn là[^.]{0,30}. Hiệu lực của mã OTP là 5 phút',
        'Don hang .{0,30} da duoc dat thanh cong. Cam on Quy khach da mua sam cung Mothercare.  Xin Quy khach luu y.{0,200}Vui long lien he hotline 1900 3038 de duoc ho tro.',
        'Mothercare Vietnam would like to annouce that.{0,60}will be moved to a new location.{0,100}',
        'Ma kich hoat tai khoan la[^.]{0,30}co hieu luc trong 5 phut, Quy khach vui long kich hoat tai khoan de trai nghiem mua sam san pham me va be tai mothercare',
        'Cam on Quy khach da dat hang tai MOTHERCARE. De cap nhat thong tin moi nhat ve CTKM hap dan, truy cap ngay http://mothercare.com.vn hoac lien he Hotline 19003038.',
        'Cam on Quy khach da dat hang tai mothercare. De cap nhat thong tin moi nhat ve mothercare, truy cap ngay https://bit.ly/.{0,20} hoac lien he Hotline 19003038.',
        'Don hang[^.]{0,30}duoc dat thanh cong. Cam on Quy khach da mua sam cung mothercare. Vui long lien he Hotline 19003038 de duoc ho tro ve thoi gian giao hang.',
        'Ban da nhan duoc.{0,200}E-code su dung.{0,100}',
        'Don hang[^.]{0,30}duoc dat thanh cong. Cam on Quy khach da mua sam cung MOTHERCARE. Vui long lien he Hotline 1900 3038 de duoc ho tro ve thoi gian giao hang.',
        'mothercare - Mã OTP của bạn là[^.]{0,30}. Hiệu lực của mã OTP là 5 phút',
        'mothercare - Ma OTP cua Quy khach la.{0,20}. Hieu luc cua ma OTP la 5 phut.',
        'mothercare - Mã OTP của bạn là .{0,10}. Hiệu lực của mã OTP là .{0,100}',
        'Mothercare gui ban e-code .{0,30} giam 1trieu5 cho combo du sinh 6trieu, giam 4trieu cho combo du sinh 15trieu.E-code su dung 1 lan den het .{0,30}',
        'Ma OTP dang nhap Mothercare Vietnam Wishlist cua ban la :[^.]{0,30}',
        'Don hang .{0,30} da duoc.{0,150}LH hotline.{0,30}Xin cam on.',
        'Don hang .{0,20} da duoc dat thanh cong. Cam on Quy khach da mua sam cung Mothercare.{0,150}Vui long lien he hotline 1900 3038 de duoc ho tro ve thoi gian giao hang. Tran trong.',
        'Ban da nhan duoc.{0,200}E-code su dung.{0,100}',
        'Don hang .{0,30} da duoc huy thanh cong. De duoc ho tro thong tin hoac dat hang lai, vui long truy cap www.mothercare.com.vn hoac LH hotline 1900 3038. Xin cam on.',
        'Don hang .{0,30}duoc.{0,100}vui long truy cap www.mothercare.com.vn hoac LH hotline.{0,30}Xin cam on.',
        'Don hang .{0,50}Cam on Quy khach da mua sam tai mothercare.{0,100}https://bit.ly/.{0,20}',
        'mothercare ra mat website TMDT.Gui tang ban code[^.]{0,50}giam 30%SP thuong hieu mothercare nguyen gia khi mua sam tai https://bit.ly/30gbK7o tu 29.9-11.10',
        'Cam on Quy khach da dat hang tai mothercare. De cap nhat thong tin moi nhat ve CTKM hap dan, truy cap ngay https://bit.ly/31mpAWK hoac lien he Hotline 19003038.',
        'Mothercare Vietnam xin thong bao.{0,60}se chuyen sang vi tri moi.{0,100}',
        'Ma kich hoat tai khoan la[^.]{0,30}co hieu luc trong 5 phut, Quy khach vui long kich hoat tai khoan de trai nghiem mua sam hang hieu chinh hang MOTHERCARE',
        'DH .{0,20} duoc dat thanh cong. Ma kiem tra DH.{0,50}tai.{0,5}https://brd.to.{0,50}Cam on QK da mua sam cung Mothercare. LH.{0,20}de duoc ho tro.',
        'DH .{0,20} duoc dat thanh cong. Ma kiem tra DH.{0,50}tai.{0,5}https://brd.to.{0,50}Cam on QK da mua sam cung Mothercare. LH.{0,20}de duoc ho tro',
        'DH .{0,20} duoc dat thanh cong. Ma kiem tra DH.{0,50}tai.{0,5}https://brd.to.{0,50}Cam on QK mua sam cung Mothercare. LH.{0,20}de duoc ho tro.',
        'Mothercare rat tiec san pham trong DH .{0,150}QK vui long kiem tra DH tai.{0,90}LH.{0,50}',
        'mothercare - Ma OTP cua ban la[^.]{0,30}. Hieu luc cua ma OTP la 5 phut',
        'Cam on ban da dat hang tai Mothercare don hang .{0,30}Mothercare.{0,150}hotline.{0,30}Don hang se bi huy.{0,100}',
        'Cam on Quy Khach.{0,50}DH.{0,80}Quy Khach.{0,50}LH.{0,20}',
        'Don hang.{0,80}Cam on.{0,80}Vui long lien he Hotline 19003038 de duoc ho tro ve thoi gian giao hang.{0,50}',
      ],
    },
  },
  {
    senderName: 'B.REPUBLIC',
    templates: {
      mobifone: [
        'Chao ban, ban dang la hang[^.]{0,30}chi can mua them[^.]{0,30}de nang hang the cung quyen loi giam[^.]{0,20}cho moi hoa don va giam 30% cho ngay sinh nhat,BR tang ma code[^.]{0,50}-giam 300k cho HD tu 3tr, a/d tu 19 - 25/8. LH: 19003038 .',
        'Cam on quy khach da dong hanh cung Banana Republic.{0,30}Kinh tang rieng QK voucher.{0,150}',
        'CHUONG TRINH DANH RIENG CHO KHACH VIP - [^.]{0,80} cho HD tu [^.]{0,30} hieu luc tu .{0,30}. CT lien he: [^.]{0,30}',
        'Chao ban, ban dang la hang[^.]{0,50}chi can mua them[^.]{0,20}de nang hang the cung quyen loi giam[^.]{0,20} cho moi hoa don va giam 30% cho ngay sinh nhat, BR tang ma code[^.]{0,50}-giam 300k cho HD tu 3tr, a/d tu 19 - 25/8. LH: 19003038 .',
        'VIP DAY! Danh tang rieng anh/chi.{0,50}tan huong dac quyen den.{0,50}nhan them qua tang cho HD tu.{0,50}',
        'Chao ban, ban dang la hang [^.]{0,50} chi can mua them [^.]{0,30} de nang hang the cung quyen loi giam [^.]{0,30} cho moi hoa don va giam [^.]{0,30} cho ngay sinh nhat, BR tang ma code .{0,50} cho HD tu [^.]{0,30}, a/d tu .{0,50}. LH: 19003038',
        'Banana Republic gui ban e-voucher tri gia .{0,100} su dung cho HD mua sam tu .{0,50}. HSD: .{0,50}. Tel: .{0,50}.',
        'Chao ban, ban dang la hang[^.]{0,30}chi can mua them[^.]{0,20}de nang hang the cung quyen loi giam[^.]{0,30}cho moi hoa don va giam 30% cho ngay sinh nhat,BR tang ma code[^.]{0,50}-giam 300k cho HD tu 3tr, a/d tu 19 - 25/8. LH: 19003038 .',
        'Gui tang Quy Khach Hang ma code.{0,150}tai https://bit.ly/.{0,150}',
        'Gui tang Quy Khach Hang ma code.{0,150}tai https://bit.ly/.{0,150}',
        'TANG RIENG QUY KHACH: Qua Tang tri an tri gia.{0,150}LH: 02838223194',
        'Tang rieng ban.{0,150}Chi tieu ngay.{0,100}khi mua sam. LH 02838223194',
        'Gui tang Quy Khach Hang ma code dac quyen.{0,100}tai https://bit.ly/.{0,30} tu.{0,50}. Ap dung dong thoi voi chuong trinh.{0,100}',
        'Happy Tet 2022! Banana Republic tang rieng quy khach.{0,120}HSD.{0,80}',
        'Cam on quy khach.{0,80}Tang rieng QK.{0,120}HSD.{0,80}',
      ],
    },
  },
  {
    senderName: 'GAP',
    templates: {
      mobifone: [
        'LOYALTY OFFER! Tang Rieng Ban ma.{0,120}tai.{0,120}',
        'Chao A/C, hang thanh vien cua A/C dang la[^.]{0,30}, chi can mua them[^.]{0,30}de nang hang thanh SILVER va duoc quyen loi giam[^.]{0,30}cua thanh vien & 30% cho ngay sinh nhat. GAP gui tang them ma[^.]{0,30}-giam 40% cho SP thu 2 a/d tu 26-30/8. LH:02838272020',
        'Chao A/C, hang thanh vien cua A/C dang la[^.]{0,30}, chi can mua them[^.]{0,30}de nang hang GOLD va duoc quyen loi giam[^.]{0,30}cua hang GOLD & 30% cho ngay SN. GAP tang them ma[^.]{0,30}de giam 400K cho bat ky HD tu 4tr a/d chung KM tai CH tu 26-30/8. LH:02838272020',
        'Chao A/C, hang thanh vien cua A/C dang la [^.]{0,50}, chi can mua them [^.]{0,50} de nang hang GOLD va duoc quyen loi giam [^.]{0,50} cua hang GOLD & 30% cho ngay SN. GAP tang them ma [^.]{0,50} de giam 400K cho bat ky HD tu 4tr a/d chung voi KM tai CH tu [^.]{0,50}. LH:02838272020',
        'Chao A/C,  da lau ban khong den GAP - GAP danh rieng uu dai " giam 40% SP thu 2" tu 22-27/7 khi doc ma XXXXXXXXXXXXX ( CT lien he nv ban hang).LH:02838272020',
        '(DANH RIENG TANG BAN) Qua tang.{0,120}Chi ap dung tai cua hang & cho sp nguyen gia.{0,50}',
        '.{0,30}Tang rieng ban ma.{0,120}Chi ap dung tai cua hang & cho sp nguyen gia.{0,50}',
        'LI XI DAC BIET! GAP tang rieng ban li xi.{0,150}khong cong gop voi CT khac.{0,100}',
        'Chao A/C, da lau A/C khong den GAP - GAP danh rieng gui ban "giam 40% SP thu 2" tu 26-30/8 khi doc ma[^.]{0,40}(CT lien he nv ban hang). LH:02838272020',
        'Chao A/C, hang thanh vien cua A/C dang la[^.]{0,30}, chi can mua them[^.]{0,30}de nang hang PLATINUM va duoc quyen loi giam[^.]{0,30}cua hang PLATINUM & 30% cho ngay SN. GAP tang them ma[^.]{0,30}giam 1tr cho bat ky HD tu 6tr a/d chung KM tai CH tu 26-30/8. LH:02838272020',
        'Chao A/C,  da lau ban khong den GAP - GAP danh rieng gui ban " giam 40% SP thu 2" tu [^.]{0,50} khi doc ma [^.]{0,50} ( CT lien he nv ban hang).LH:02838272020',
        'Chao A/C, hang thanh vien cua A/C dang la [^.]{0,50}, chi can mua them [^.]{0,30} de nang hang thanh SILVER va duoc quyen loi giam [^.]{0,30} cua thanh vien & 30% cho ngay sinh nhat. GAP gui tang them ma [^.]{0,50} cho SP thu 2 a/d tu [^.]{0,30}. CTiet: 02838272020',
        "VIP's DAY - Nhan binh nuoc GAP tri gia 500k khi mua HD bat ky (SL co han, khong a/d CH Noi Bai).Doc ma [^.]{0,50} de duoc a/dung. Receive GAP water bottle value 500K for any purchase from 17-19/7 (limited qty, exclude Noi Bai), show code VIPGAP0001 to be applied. 02838272020",
        "VIP's DAY - Receive GAP water bottle value 500K for any purchase from 17-19/7 (limited qty, exclude Noi Bai), show code [^.]{0,50} to be applied. 02838272020",
        'Chuong trinh DANH RIENG CHO VIP-Nhan binh nuoc GAP tri gia 500k khi mua HD bat ky tu 17-19/7 (SL co han).Doc ma [^.]{0,50} cho NV de duoc a/dung.CT:02838272020.',
        'DANH RIENG CHO VIP-Nhan binh nuoc GAP tri gia 500k khi mua HD bat ky tu 17-19/7 (SL co han, khong a/d CH Noi Bai).Doc ma [^.]{0,50} de duoc a/dung. 02838272020.',
        'VIP’s DAY – Receive GAP water bottle value 500K for any purchase from 17-19/7 (limited qty, exclude Noi Bai), show code [^.]{0,50} to be applied. 02838272020',
        'Chao A/C, hang thanh vien cua A/C dang la [^.]{0,50}, chi can mua them [^.]{0,50} de nang hang PLATINUM va duoc quyen loi giam [^.]{0,50} cua hang PLATINUM & 30% cho ngay SN. GAP tang them ma [^.]{0,50} giam 1tr cho bat ky HD tu 6tr a/d chung voi KM tai CH tu [^.]{0,50}. LH:02838272020',
        'VIP’s DAY - Nhan binh nuoc GAP tri gia 500k khi mua HD bat ky (SL co han, khong a/d CH Noi Bai).Doc ma [^.]{0,50} de duoc a/dung. Receive GAP water bottle value 500K for any purchase from 17-19/7 (limited qty, exclude Noi Bai), show code VIPGAP0001 to be applied. 02838272020',
        'CHUONG TRINH DANH RIENG CHO KHACH VIP - [^.]{0,200} cho HD tu [^.]{0,100} hieu luc tu .{0,30}. CT lien he hotline: [^.]{0,30}',
        'Chuc mung ban nhan duoc.{0,80}Ap dung.{0,80}HSD.{0,100}',
      ],
    },
  },
  {
    senderName: 'OLD NAVY',
    templates: {
      mobifone: [
        'CHUONG TRINH DANH RIENG CHO KHACH VIP - [^.]{0,200} cho HD tu [^.]{0,100} hieu luc tu .{0,30}. CT lien he hotline: [^.]{0,30}',
        '.{0,50}Qua tang KH than thiet danh rieng cho ban.{0,200}',
        '.{0,100}mua sam tai Old Navy. Ma qua tang.{0,200}',
        'Chao ban, ban dang la thanh vien hang [^.]{0,50} chi can mua them [^.]{0,20} de nang hang the cung quyen loi giam [^.]{0,20} cho moi hoa don va giam 30% cho ngay sinh nhat, ON tang ma code [^.]{0,50}- giam 200k cho HD tu 1.5tr, a/d tu 28 - 31/7. LH: 19003038 .',
        'Chao ban, ban dang la thanh vien hang [^.]{0,50} chi can mua them [^.]{0,20} de nang hang the cung quyen loi giam [^.]{0,20} cho moi hoa don va giam 30% cho ngay sinh nhat, ON tang ma code [^.]{0,50}- giam 200k cho HD tu 1.5tr, a/d tu 28 - 31/7. LH: 19003038 .',
        '.{0,50}DANH CHO RIENG BAN tai Old Navy. Ma code.{0,200}',
        'Li xi dau nam! Old Navy li xi rieng.{0,200}Khong ap dung cung CT khac. LH: 02839158898',
        'Chao ban, ban dang la thanh vien hang [^.]{0,50} chi can mua them [^.]{0,20} de nang hang the cung quyen loi giam [^.]{0,20} cho moi hoa don va giam 30% cho ngay sinh nhat, ON tang ma code [^.]{0,50}- giam 200k cho HD tu 1.5tr, a/d tu 28 - 31/7. LH: 19003038 .',
        'Chuc mung ban nhan duoc.{0,100}Ap dung cung.{0,100}HSD.{0,100}',
        'OLD NAVY LI XI DAU NAM! Old Navy.{0,50}tang quy khach.{0,100}duoc ap dung chung voi cac chuong trinh khac tai cua hang.HSD.{0,100}',
      ],
    },
  },
  {
    senderName: 'MANGO',
    templates: {
      mobifone: [
        'Cam on quy khach da dong hanh cung MANGO nhieu nam qua!Kinh tang rieng.{0,160}Hay den ngay cua hang MANGO gan nhat.{0,80}',
        'Cam on quy khach da dong hanh cung MANGO nhieu nam qua!Kinh tang rieng.{0,160}AP DUNG TAI CAC CH TREN TOAN QUOC.{0,50}',
        '(Chuc mung sinh nhat quy khach hang)',
        'MANGO-CHUONG TRINH KHACH HANG THAN THIET danh rieng den [^.]{0,50} giam [^.]{0,50} cho tat ca sp moi tu 1/8-1/9 ap dung tai HTCH Mango: http://bit.ly/HTCH_Mango .',
        'MANGO danh tang rieng Quy Khach.{0,150}http://bit.ly/.{0,30}',
        'MANGO TRI AN KHACH HANG voi chuong trinh danh rieng cho ban ma[^.]{0,50}: giam 10% voi 1 sp, 20% voi 2 sp va 30% khi mua tu 4 sp (kg ap dung phu kien) den het 7/10. Xuat trinh tn tai thu ngan de duoc ap dung. HTCH Mango: http://bit.ly/HTCH_Mango',
        'MANGO danh rieng tang ban ma code[^.]{0,40}giam them 10% tren hang muc thanh vien.{0,50}hien tai, chi tu 1/9-1/10 tai HTCH Mango: http://bit.ly/HTCH_Mango.',
        'MANGO. BLACK VIP PARTY. TANG RIENG BAN.{0,100}AP DUNG TAI.{0,80}LH.{0,30}',
        'MANGO. Chuc mung quy khach nhan duoc.{0,100}Hay den ngay cua hang MANGO gan nhat. HSD.{0,100}',
        'MANGO. TANG RIENG BAN.{0,50}KHI MUA SP NGUYEN GIA.{0,100}AP DUNG TAI.{0,100}',
      ],
    },
  },
  {
    senderName: 'NIKE',
    templates: {
      mobifone: [
        'Chuc mung ban duoc tham gia.{0,70}So raffle cua ban la.{0,50}Don xem livestream Raffle.{0,100}',
        'Cam on quy khach da dong hanh cung Nike ACFC. Dung quen su dung.{0,150}',
        'Cam on quy khach da dong hanh cung Nike.{0,100}tang.{0,100}Su dung.{0,50}',
        'Cam on quy khach da dong hanh cung Nike. Dung quen su dung.{0,150}',
        'Cam on quy khach da dong hanh cung Nike trong nam 2020. Nike ACFC tang ban E-voucher.{0,150}',
        'Dung quen cung Nike tap luyen the thao ban nhe. Nike ACFC tang ban.{0,200}',
        'Ban chi can mua them.{0,150}Nike ACFC gui tang E-voucher.{0,200}',
        'Your Nike verification code is: .{0,30}',
        'Dung quen cung Nike tap luyen the thao ban nhe. Nike ACFC tang ban E-voucher[^.]{0,50}tri gia 500k su dung cho HD tu 1,500,000. Ap dung tu 18/9-30/9/2020',
        'Ban chi can mua them.{0,50}de giu hang[^.]{0,50}.Nike ACFC gui tang E-voucher[^.]{0,50}tri gia 1 trieu cho HD tu 3 trieu. Ap dung tu 18/9-30/9/2020',
        'Ban chi can mua them.{0,50}de giu hang[^.]{0,50}.Nike ACFC gui tang E-voucher[^.]{0,50}tri gia 500k cho HD tu 1 trieu ruoi. Ap dung tu 18/9-30/9/2020',
        'Ban chi can mua them.{0,50}de nang hang[^.]{0,50}.Nike ACFC gui tang E-voucher[^.]{0,50}tri gia 1 trieu cho HD tu 3 trieu. Ap dung tu 18/9-30/9/2020',
        'Ban chi can mua them.{0,50}de nang hang[^.]{0,50}.Nike ACFC gui tang E-voucher[^.]{0,50}tri gia 500k cho HD tu 1 trieu ruoi. Ap dung tu 18/9-30/9/2020',
        'Quy khach chi can mua them[^.]{0,50}de nang hang[^.]{0,30}.Nike ACFC gui tang E-voucher[^.]{0,30}tri gia 500k cho HD tu 2 trieu. Ap dung tu 21/8-31/8/2020',
        'Quy khach chi can mua them[^.]{0,50}de nang hang[^.]{0,30}.Nike ACFC gui tang E-voucher[^.]{0,30}tri gia 300k cho HD tu 1 trieu. Ap dung tu 21/8-31/8/2020',
        'Quy khach chi can mua them[^.]{0,50}de nang hang[^.]{0,30}.Nike ACFC gui tang E-voucher[^.]{0,30}tri gia 500k cho hoa don tu 2 trieu. Ap dung tu 21/8-31/8/2020',
        'Your Nike mobile phone verification code is .{0,30}',
        'Quy khach chi can mua them[^.]{0,50}de nang hang[^.]{0,30}.Nike ACFC gui tang E-voucher[^.]{0,30}tri gia 300k cho hoa don tu 1 trieu. Ap dung tu 21/8-31/8/2020',
        'Chuc mung nam moi.NIKE ACFC Cty Au Chau xin gui tang quy khach E-Voucher [^.]{0,30} tri gia .{0,20} dung cho hoa don mua hang tu .{0,30}.Hieu luc tu .{0,40}',
        'Chuc mung ban co co hoi tham gia Raffle Air Jordan 1 Royal Toe. So raffle cua ban la:[^.]{0,30}. Don xem livestream Raffle tren The Swoosh fanpage vao 20h ngay 4.8',
        'Cam on quy khach hang da dong hanh cung Nike.Nike ACFC gui quy khach E-voucher [^.]{0,30} tri gia .{0,20} cho hoa don tu .{0,20}. Ap dung tu .{0,30}',
        'Hay tang cuong tap luyen de nang cao suc khoe &Dung quen su dung ma HPBD giam30% .{0,30} tai cac CH NIKE_ACFC truoc 31/3/20.Chi tiet http://bit.ly/HPBDACFC .',
        'Your NikePlus account has been locked due to multiple login attempts. To unlock your account, please reset your password: www.nike.com/resetpassword',
        'Congratulations on becoming a NikePlus member,.{0,30}.Immediately bind with our NIKE official WeChat to unlock personalized service and exclusive offers. Or learn more about NikePlus here <https://swoo.sh/.{0,15}>',
        'Click to reset your password here: www.nike.com/resetpassword. This link will expire in 48 hours. If the password reset is not initiated by you, please ignore.',
        'Unfortunately, you did not get this Nike product priority purchase rights. But do not lose heart, with the phone to continue to trigger your Nike NBA Connected Jersey, will have the opportunity to unlock more awards.',
        'Congratulations on the right to purchase Nike products! Quickly use your phone to trigger your Nike NBA Connected Jersey for more information.',
        'Unfortunately, you did not smoke the tickets for this tournament. But do not lose heart, with the phone to continue to trigger your Nike NBA Connected Jersey, will have the opportunity to unlock more awards!',
        'Congratulations to get the tickets! Please use your phone to trigger your Nike NBA Connected Jersey for more information.',
        'Your .{0,15} order .{0,15} is ready for pick up. Store Hours are .{0,50}',
        'Your .{0,15} order has been .{0,15} picked up. Thank you.',
        'Congratulations you have your own Nike NBA Connected Jersey. Use the phone to trigger the shirt, unlock the NBA game wonderful moments, star song singles, Nike product priority purchase rights exclusive reward.',
        'Your .{0,15} order .{0,15} is now being prepped. We estimate a wait time of .{0,20}',
        'Your .{0,15} order .{0,15} is now being processed. We estimate a wait time of .{0,20}.',
        'Your Nike mobile phone verification code is .{0,10}',
        'Nike Code: .{0,10}.',
        'NIKE: Access your favorites here: .{0,20}. Msg & data rates may apply. Reply HELP for help, STOP to cancel.',
        'Nike Orders: Your order# .{0,15} has arrived! To see the items, open the package - or check here https://swoo.sh/MyOrder?orderId.{0,20}',
        'Nike Orders: Your order# .{0,15} has been received. You can check the status of it here at any time https://swoo.sh/MyOrder?orderId.{0,20}',
        'Nike Orders: Your order# .{0,15} is on its way. You can track it at any time here https://swoo.sh/MyOrder?orderId.{0,20}',
        'NIKE gui khach hang E-voucher.{0,100}HSD.{0,30}LH.{0,50}',
        'NIKE sends you an E-voucher.{0,100}EXP.{0,30}Hotline.{0,50}',
      ],
    },
  },
  {
    senderName: 'FITFLOP',
    templates: {
      mobifone: [
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them.{0,150}cho HD nguyen gia.{0,100}',
        'Thank you for choosing FITFLOP. You only need.{0,150}Upgrade now at FITFLOP.{0,150}',
        'Thank you for choosing FitFlop. Enjoy.{0,100}in your birthday month. Please bring ID card, SMS to apply.{0,100}More info http://bit.ly/HPBDACFC',
        'Thank you for choosing FITFLOP. You only need.{0,150}for full price bills.{0,100}',
        'Thank you for choosing FITFLOP. You only need.{0,130}for full price bills from.{0,40}',
        'Cam on quy khach da dong hanh cung FITFLOP. Dung quen su dung Happy Birthday Code.{0,150}Vui long mang CMND, SMS den CH. Chi tiet http://bit.ly/HPBDACFC',
        'Thank you for choosing FITFLOP. You only need.{0,200}Enjoy cashback.{0,100}',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them.{0,130}cho HD nguyen gia.{0,40}',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them.{0,150}Den CH FitFlop de.{0,150}',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them.{0,200}Nhan ngay.{0,100}',
        'Thank you for choosing FITFLOP. You only need.{0,130}for full price bills from.{0,40}',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them.{0,130}cho HD nguyen gia.{0,40}',
        'Ban da nhan duoc.{0,70}su dung tai CH FitFlop tren toan quoc. Ecode ap dung khi dang ky thanh vien ACFC & hoa don nguyen gia.{0,70}https://bit.ly/.{0,30}',
      ],
      vinaphone: [
        'Thank you for choosing FITFLOP. You only need [^.]{0,50}. Enjoy E-voucher [^.]{0,50} for full price bills from [^.]{0,20}. Upgrade now at FITFLOP from [^.]{0,30}',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them [^.]{0,50}. FITFLOP gui tang E-voucher [^.]{0,50} cho HD nguyen gia tu [^.]{0,30}',
        'Thank you for choosing FITFLOP. You only need [^.]{0,80}. Enjoy E-voucher [^.]{0,50} for full price bills from [d.]{0,10}K. [^.]{0,50}',
        'Thank you for choosing FITFLOP. You only need [^.]{0,50}. Enjoy E-voucher [^.]{0,50} for full price bills from [^.]{0,20}. Upgrade now at FITFLOP from [^.]{0,30}',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them [^.]{0,30} de giu hang [^.]{0,20}. FITFLOP gui tang E-voucher [^.]{0,60} cho HD nguyen gia tu 1.500K tu [^.]{0,30}. Nhan ngay 100.000D cho hd tu 1tr, tu 22-30/4 toan quoc.',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them [^.]{0,30} de nang hang [^.]{0,20}. FITFLOP gui tang E-voucher [^.]{0,60} cho HD nguyen gia tu 1.500K. Den CH FitFlop de nang hang [^.]{0,30}. Nhan ngay 100.000D cho hd tu 1tr, tu 22-30/4 toan quoc.',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them [^.]{0,50}. FITFLOP gui tang E-voucher [^.]{0,50} cho HD nguyen gia tu [d.]{0,10}K. Den CH FitFlop [^.]{0,50}',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them [^.]{0,50}. FITFLOP gui tang E-voucher [^.]{0,50} cho HD nguyen gia tu [^.]{0,20}. Den CH FitFlop de nang hang [^.]{0,30}',
        'Thank you for choosing FITFLOP. You only need [^.]{0,30} to upgrade to[^.]{0,20}. Enjoy E-voucher [^.]{0,30}58 value of 500K for full price bills from 1.500K. Upgrade now at FITFLOP from [^.]{0,30}. Enjoy cashback VND 100K for bills from VND 1million from Apr22-30 storewide.',
        'Cam on quy khach da dong hanh cung FITFLOP. Dung quen su dung Happy Birthday Code [^.]{0,50} tai CH FITFLOP va nhan qua tri gia [^.]{0,20}. Ap dung den [^.]{0,30}. Vui long mang CMND, SMS den CH. Chi tiet http://bit.ly/HPBDACFC',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them [^.]{0,50}. FITFLOP gui tang E-voucher [^.]{0,50} cho HD nguyen gia tu [^.]{0,20}. Den CH FitFlop de nang hang [^.]{0,30}',
        'Thank you for choosing FITFLOP. You only need [^.]{0,30} to maintain your current member level of [^.]{0,20}. Enjoy E-voucher [^.]{0,60} for full price bills from 1.500K from [^.]{0,30}. Enjoy cashback VND 100K for bills from VND 1million from Apr22-30 storewide.',
        'Thank you for choosing FITFLOP. You only need [^.]{0,30} to maintain your current member level of [^.]{0,20}. Enjoy E-voucher [^.]{0,50} for full price bills from [^.]{0,40}',
        'Thank you for choosing FITFLOP. You only need [^.]{0,30} to upgrade to [^.]{0,20}. Enjoy E-voucher [^.]{0,30} value of 500K for full price bills from 1.500K. Upgrade now at FITFLOP from [^.]{0,30}. Enjoy cashback VND 100K for bills from VND 1million from Apr22-30 storewide.',
        'Thank you for choosing FITFLOP. You only need [^.]{0,30} to maintain your current member level of [^.]{0,20}. Enjoy E-voucher [^.]{0,50} for full price bills from [^.]{0,40}',
        'Cam on da dong hanh cung FITFLOP. Ban chi can mua them [^.]{0,50}. FITFLOP gui tang E-voucher [^.]{0,50} cho HD nguyen gia tu [^.]{0,30}',
        'Thank you for choosing FitFlop. Enjoy 30% off to purchase FitFlop shoes and receive a gift value of [^.]{0,10} in your birthday month. Please bring ID card, SMS to apply code [^.]{0,50}. More info http://bit.ly/HPBDACFC',
      ],
    },
  },
  {
    senderName: 'TOMMY',
    templates: {
      mobifone: [
        'TOMMY HILFIGER - To be VIP member just spend 3mil more. Tommy offers.{0,50}for full-price items at.{0,100}',
        'TOMMY HILFIGER- A special gift for Tommy member.{0,50}for full-price items. Apply.{0,100}',
        'TOMMY HILFIGER - To be .{0,50} Tommy offers .{0,50} for full price items at all Tommy stores .{0,30}',
        'TOMMY HILFIGER - To be.{0,100}for full-price items.{0,50}Tel 02839397999',
        'TOMMY HILFIGER-Danh tang thanh vien VIP.{0,100}Ap dung.{0,100}',
        'TOMMY HILFIGER - A special gift for.{0,150}Apply.{0,70}',
        'TOMMY HILFIGER - Danh tang thanh vien.{0,150}Ap dung.{0,70}',
        '(Chuc mung sinh nhat quy khach hang)',
        'TOMMY HILFIGER- A special gift for .{0,100} cho hang nguyen gia/for full price items. Ap dung .{0,50} tai CH Tommy/ at Tommy stores',
        'TOMMY HILFIGER – Danh tang thanh vien Tommy Ecode.{0,50}hang nguyen gia tu.{0,30}tai tat ca CH Tommy. LH 02839397999',
        'TOMMY HILFIGER - Danh tang thanh vien VIP hang the .{0,100} hang nguyen gia. Ap dung .{0,30} tai tat ca CH Tommy',
        'TOMMY HILFIGER- Danh tang/ Gift for Tommy member.{0,50}cho hang nguyen gia/full-price item. Ap dung/Apply.{0,100}',
        'TOMMY HILFIGER - Danh tang thanh vien Tommy.{0,50}hang nguyen gia tu.{0,100}',
        'TOMMY HILFIGER- Danh tang/ Gift for Tommy member Ecode.{0,50}cho hang nguyen gia/full-price item. Ap dung/Apply.{0,100}',
        'TOMMY HILFIGER - Tang thanh vien.{0,100} hang nguyen gia. Ap dung tu .{0,30}tai tat ca CH Tommy. Hotline 02839397999',
        'TOMMY HILFIGER- A special gift for Tommy member.{0,50}for full-price items. Apply.{0,30}at all Tommy stores. Tel 0283939799',
        'TOMMY HILFIGER - Danh tang thanh vien Tommy Ecode.{0,50}hang nguyen gia tu.{0,30}tai tat ca CH Tommy. LH 02839397999',
        'TOMMY HILFIGER - Chi con thieu.{0,100}hang nguyen gia. Ap dung tu.{0,50}LH 02839397999',
        'TOMMY HILFIGER - Chi con thieu .{0,50} Tommy tang ban .{0,50} hang nguyen gia. Ap dung tu .{0,30} tai tat ca CH Tommy',
        'TOMMY HILFIGER - A special gift for .{0,100} for full price items. Apply on .{0,30} at all Tommy stores',
        'TOMMY HILFIGER - Chi con thieu 3 trieu de nang hang VIP. Tommy tang ban.{0,50}hang nguyen gia. Ap dung.{0,100}',
        'TOMMY HILFIGER- Danh tang/ Gift for Tommy member.{0,100}Ap dung/Apply.{0,100}',
        'TOMMY HILFIGER - A special gift for Tommy member.{0,50}for full-price items. Apply.{0,100}',
        'TOMMY HILFIGER-chi voi hoa don 3 trieu de duy tri hang thanh vien. Tommy tang.{0,60}hang nguyen gia. Ap dung.{0,60}',
        'TOMMY HILFIGER-spend 3mil VND to keep your membership tier with.{0,60}applied on full price bill at stores.{0,60}',
        'TOMMY HILFIGER - spend 3mil VND to keep your membership tier with.{0,60}applied on full price bill at stores.{0,30}Chi voi hoa don 3 trieu de duy tri hang thanh vien. Tommy tang.{0,60}hang nguyen gia. Ap dung.{0,60}',
        'TOMMY HILFIGER - Chi con thieu 3 trieu de nang hang thanh vien. Tommy tang.{0,60}hang nguyen gia. Ap dung.{0,60}',
        'TOMMY HILFIGER-chi voi hoa don 3 trieu de duy tri hang thanh vien. Tommy tang.{0,60}hang nguyen gia. Ap dung.{0,60}',
        'TOMMY HILFIGER-spend 3mil VND to keep your membership tier with.{0,60}applied on full price bill at stores.{0,60}',
        'TOMMY HILFIGER - spend 3mil VND to keep your membership tier with.{0,60}applied on full price bill at stores.{0,30}Chi voi hoa don 3 trieu de duy tri hang thanh vien. Tommy tang.{0,60}hang nguyen gia. Ap dung.{0,60}',
        'TOMMY HILFIGER - Chi con thieu 3 trieu de nang hang thanh vien. Tommy tang.{0,60}hang nguyen gia. Ap dung.{0,60}',
        'TOMMY HILFIGER-spend 3mil VND to upgrade your membership tier with.{0,60}applied on full price bill at stores from.{0,60}',
        'TOMMY HILFIGER - spend 3mil VND to upgrade your membership tier with.{0,60}applied on full price bill at stores.{0,30}Chi con thieu 3 trieu de nang hang thanh vien. Tommy tang.{0,60}hang nguyen gia. Ap dung.{0,60}',
      ],
    },
  },
  {
    senderName: 'PARFOIS',
    templates: {
      mobifone: [
        'STUDENT OFFER. Tu nay, PARFOIS uu ai danh tang.{0,100}What u waiting for! Ds cua hang http://bit.ly/.{0,30}',
        'Chuc mung nam moi! PARFOIS danh rieng cho thanh vien IPPG. Sam Tet ngay voi code.{0,50}toan bo san pham thoi trang phu kien PARFOIS. Ap dung tu.{0,50}Danh sach cua hang: http://bit.ly/StorePAF',
        '.{0,50}Than moi.{0,100}voi nhieu hoat dong va qua tang hap dan danh rieng cho khach VIP nhan duoc tin nhan.{0,150}',
        'HAPPY 2nd ANNIVERSARY! Than moi.{0,100}voi nhieu hoat dong va qua tang hap dan danh rieng cho khach VIP nhan duoc tin nhan. GIAM 20% tat ca san pham chi 1 ngay duy nhat 24/01 tai PARFOIS The Garden Shopping Center.',
        'PARFOIS DANH RIENG CHO.{0,150}tai CH PARFOIS voi.{0,30}',
        'PARFOIS UU DAI DANH RIENG CHO.{0,150}tai CH PARFOIS voi.{0,30}',
        '(Chuc mung sinh nhat quy khach hang)',
        'PARFOIS tang ban NEN THOM CAO CAP & HOAN TIEN.{0,100}LH CH de biet them c/tiet http://bit.ly/.{0,30}',
        'STUDENT OFFER. Tu nay, PARFOIS uu ai danh tang.{0,100}What u waiting for! Ds cua hang http://bit.ly/.{0,30}',
        'PARFOIS Chuc mung.{0,40}da tro thanh KH mua sam tai Parfois nhieu nhat trong.{0,50}Than tang ban.{0,80}Su dung ngay code.{0,30} tai website: https://bit.ly/.{0,30}',
        'Congratulation becoming the top spenders at PARFOIS.{0,50}Give you gift voucher.{0,100}Shop now at https://bit.ly/.{0,30}',
      ],
    },
  },
  {
    senderName: 'DUNE',
    templates: {
      mobifone: [
        'Cam on da dong hanh cung Dune London. Ban chi can mua them.{0,50}Dune London gui tang.{0,120}CH Dune London de.{0,50}',
        'Thank you for choosing Dune London. You only need.{0,60}Enjoy E-voucher.{0,120}at Dune London.{0,40}',
        'Cam on da dong hanh cung Dune London. Ban chi can mua them.{0,50}Dune London gui tang.{0,120}',
        'Thank you for choosing Dune London. You only need.{0,100}Enjoy E-voucher.{0,80}from.{0,40}',
        'Thank you for choosing DUNE. You only need.{0,200}price bills.{0,120}',
        'Cam on da dong hanh cung DUNE. Ban chi can mua them.{0,150}cho HD nguyen gia.{0,100}',
        'Thank you for choosing DUNE. You only need.{0,150}for full price bills.{0,100}',
        "HAPPY NEW YEAR. We've missed you. Dune offers.{0,150}Applied storewide.{0,50}",
        'HAPPY NEW YEAR. DUNE tang ban.{0,150}Ap dung tai.{0,50}',
        'Thank you for choosing DUNE. You only need.{0,100}Come now to nearest.{0,100}',
        'Cam on ban dong hanh cung DUNE. Ban chi can.{0,100}Den cua hang.{0,100}',
        'You only need to purchase.{0,100}Come now to your nearest DUNE LONDON.{0,30}',
        'Ban chi can mua them.{0,100}Den cua hang DUNE LONDON gan nhat.{0,50}',
        'Cam on quy khach da dong hanh cung DUNE LONDON. Dung quen su dung.{0,120}Vui long mang CMND, SMS den CH. Chi tiet http://bit.ly/.{0,30}',
        'Thank you for choosing DUNE LONDON. Enjoy 30% off to purchase DUNE shoes, accessories in your birthday month. Please bring ID card, SMS to apply code.{0,100}More info http://bit.ly/.{0,30}',
        'Cam on quy khach da dong hanh cung DUNE. Dung quen su dung.{0,200}Vui long mang CMND, SMS den CH. Thank you for choosing DUNE. Enjoy .{0,200}More info http://bit.ly/.{0,30}',
        'Cam on quy khach da dong hanh cung DUNE. Dung quen su dung.{0,200}Vui long mang CMND, SMS den CH. Chi tiet http://bit.ly/.{0,30}',
        'Cam on quy khach da dong hanh cung DUNE. Dung quen su dung.{0,200}Vui long mang CMND, SMS den CH. Thank you for choosing DUNE. Enjoy .{0,200}More info http://bit.ly/.{0,30}',
        'Thank you for choosing DUNE. Enjoy 30% off for full price,10 million max/bill in your birthday month. Please bring ID card, SMS to apply code BD123456789010 at DUNE until Dec31. More info http://bit.ly/HPBDACFC',
        'Cam on quy khach da dong hanh cung DUNE. Dung quen su dung.{0,200}Vui long mang CMND, SMS den CH. Chi tiet http://bit.ly/.{0,30}',
        '(Chuc mung sinh nhat quy khach hang)',
        'Cam on da dong hanh cung Dune London. Ban chi can mua them.{0,50}Dune London gui tang.{0,1200}CH Dune London de.{0,50}',
        'Thank you for choosing Dune London. You only need.{0,60}Enjoy E-voucher.{0,120}at Dune London.{0,40}',
        'Cam on da dong hanh cung Dune London. Ban chi can mua them.{0,50}Dune London gui tang.{0,120}',
        'Thank you for choosing Dune London. You only need.{0,100}Enjoy E-voucher.{0,80}from.{0,40}',
      ],
    },
  },
  {
    senderName: 'FCUK',
    templates: {
      mobifone: [
        '.{0,50}FCUK chuc mung Anh/Chi nhan duoc code.{0,150}Vui long trinh CMND & SMS',
        'French Connection chuc mung Anh/Chi nhan duoc code.{0,150}Vui long trinh CMND & SMS',
      ],
    },
  },
  {
    senderName: 'OVS',
    templates: {
      mobifone: [
        'OVS tang rieng ban.{0,150}OVS offers you.{0,100}',
        'Tri an KH than thiet,OVS tang rieng cho ban.{0,100}Vui long mang theo TN de nhan qua.{0,50}',
        'OVS tang ban.{0,80}mua hang.{0,80}OVS offers you.{0,100}',
      ],
      vinaphone: [
        'OVS gui tang ban[^.]{0,20}ma voucher [^.]{0,50} mua hang tai [^.]{0,80}',
        'OVS offers you[^.]{0,20}a code[^.]{0,30}of gift voucher with value of[^.]{0,70}an expiration date of[^.]{0,10}',
        'OVS tang ban[^.]{0,20}ma voucher[^.]{0,60}mua hang tai[^.]{0,90}. OVS offers you a [^.]{0,40}',
        'Tri an KH than thiet,OVS tang rieng cho ban [^.]{0,100}.Vui long mang theo TN de nhan qua.LH:[^.]{0,30}',
      ],
    },
  },
  {
    senderName: 'TYPO',
    templates: {
      mobifone: [
        'TYPO gui tang khach yeu ma.{0,80}khi mua san pham nguyen gia tai cua hang Typo. HSD.{0,80}',
      ],
      vinaphone: [
        'TYPO gui tang [^.]{0,15} ma [^.]{0,55} khi mua san pham nguyen gia tai cua hang Typo. HSD [^.]{0,20}. LH: [^.]{0,15}',
      ],
    },
  },
  {
    senderName: 'COTTON ON',
    templates: [],
  },
];
const tmpMNOList = tmpSMSSenderList.filter(
  (smsSender) => smsSender.senderName ==='ACFC'
);
console.log('Content options: ', tmpMNOList);
